name: frieren 
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - pytorch-cuda=12.4
  - pip
  - pandas
  - protobuf
  - grpcio
  - ninja
  - numpy
  - sentencepiece
  - uvicorn
  - pip:
    - accelerate
    - bitsandbytes
    - datasets
    - diffusers
    - transformers
    - twirp
